### ISSUE TITLE
Correct link for [Taylor, 1997] book reference in notebooks/L2/least-squares.ipynb

### ISSUE THREAD

**Issue by joaoambiente** [IntroQG/site#124]
Hi,

The correct link for [Taylor, 1997](http://www.uscibooks.com/taylornb.htm) in https://github.com/IntroQG/site/blob/master/source/notebooks/L2/least-squares.ipynb is:

https://uscibooks.aip.org/books/an-introduction-to-error-analysis-the-study-of-uncertainties-in-physical-measurements-third-edition/

The current link is obsolete.

Cheers!

**Comment by davewhipp** [comment]
Thanks for noticing @joaoambiente ! I've updated the link in the text in 1020880e9bdca6b30e67b0117d19188fc4a67096.
